#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use karmabunny\kb\Generate;
use karmabunny\kb\XML;

function main() {
    echo "fetch...\n";

    $zones = [];
    $countries = [];
    $alt = [];

    $url = 'https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml';
    $xml = file_get_contents($url);
    $doc = XML::parse($xml);

    $map = XML::xpath($doc, '//mapZone', 'list');

    foreach ($map as $zone) {
        $win = XML::attr($zone, 'other');
        $iana = XML::attr($zone, 'type');
        $territory = XML::attr($zone, 'territory');

        $iana = str_replace('Etc/GMT', 'GMT', $iana);
        $iana = str_replace('Etc/UTC', 'UTC', $iana);

        if ($territory === '001') {
            $zones[$win] = $iana;
        }
        else {
            $ianas = explode(' ', $iana);

            foreach ($ianas as $iana) {
                $alt[$iana] = $win;
                $countries[$iana] = $territory;
            }
        }
    }

    echo "Found " . count($zones) . " windows zones\n";
    echo "Found " . count($countries) . " countries\n";

    $zones['__rev__'] = $alt;

    // Write windows timezones.
    $target = __DIR__ . '/../src/config/tzwin.php';
    $writer = new Generate($target);

    $writer->comment("This file is autogenerated");
    $writer->comment(date('Y-m-d H:i:s'));
    $writer->write($zones);

    echo "Written to {$target}\n";

    // Write iana territories.
    $target = __DIR__ . '/../src/config/tzcountry.php';
    $writer = new Generate($target);

    $writer->comment("This file is autogenerated");
    $writer->comment(date('Y-m-d H:i:s'));
    $writer->write($countries);

    echo "Written to {$target}\n";
}

main();
